name: Check Dockerfile

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t vhp_platform:latest .

      - name: Run Docker container to check
        run: docker run --rm vhp_platform:latest
